name: gpay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dotted_border: ^2.1.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/india_flag.png
    - assets/images/google_pay.png
    - assets/images/vector_1.png
    - assets/images/no_user.png
    - assets/images/vector_2.png
    - assets/images/home_banner.png