// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGFJPcFfKkOzCn3jruM2piT7HlPqfaNlA',
    appId: '1:1075340627903:web:4d7ce3e58083782acbdb0a',
    messagingSenderId: '1075340627903',
    projectId: 'gpayclone-6bc7b',
    authDomain: 'gpayclone-6bc7b.firebaseapp.com',
    storageBucket: 'gpayclone-6bc7b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJne8do5frwLKsuoyiX9tI7A4DcnjvcAE',
    appId: '1:1075340627903:android:257e794f85ad2714cbdb0a',
    messagingSenderId: '1075340627903',
    projectId: 'gpayclone-6bc7b',
    storageBucket: 'gpayclone-6bc7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-Xae-YLb6RfxwxnN0jT0LB-Inj33uw0',
    appId: '1:1075340627903:ios:94ae4475f67f0322cbdb0a',
    messagingSenderId: '1075340627903',
    projectId: 'gpayclone-6bc7b',
    storageBucket: 'gpayclone-6bc7b.firebasestorage.app',
    iosBundleId: 'com.example.gpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy-Xae-YLb6RfxwxnN0jT0LB-Inj33uw0',
    appId: '1:1075340627903:ios:94ae4475f67f0322cbdb0a',
    messagingSenderId: '1075340627903',
    projectId: 'gpayclone-6bc7b',
    storageBucket: 'gpayclone-6bc7b.firebasestorage.app',
    iosBundleId: 'com.example.gpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGFJPcFfKkOzCn3jruM2piT7HlPqfaNlA',
    appId: '1:1075340627903:web:750358e5cb55493acbdb0a',
    messagingSenderId: '1075340627903',
    projectId: 'gpayclone-6bc7b',
    authDomain: 'gpayclone-6bc7b.firebaseapp.com',
    storageBucket: 'gpayclone-6bc7b.firebasestorage.app',
  );
}
